export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_PRODUCT_FAILURE = "LOAD_PRODUCT_FAILURE";
export const UPDATE_RATING = "UPDATE_RATING";
export const UPDATE_REVIEWS = "UPDATE_REVIEWS";
